const Ziggy = {
    url: 'http:\/\/localhost:8000',
    port: 8000,
    defaults: {},
    routes: {
        'debugbar.openhandler': { uri: '_debugbar\/open', methods: ['GET', 'HEAD'] },
        'debugbar.clockwork': { uri: '_debugbar\/clockwork\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'debugbar.telescope': { uri: '_debugbar\/telescope\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'debugbar.assets.css': { uri: '_debugbar\/assets\/stylesheets', methods: ['GET', 'HEAD'] },
        'debugbar.assets.js': { uri: '_debugbar\/assets\/javascript', methods: ['GET', 'HEAD'] },
        'debugbar.cache.delete': {
            uri: '_debugbar\/cache\/{key}\/{tags?}',
            methods: ['DELETE'],
            parameters: ['key', 'tags'],
        },
        'debugbar.queries.explain': { uri: '_debugbar\/queries\/explain', methods: ['POST'] },
        'horizon.stats.index': { uri: 'horizon\/api\/stats', methods: ['GET', 'HEAD'] },
        'horizon.workload.index': { uri: 'horizon\/api\/workload', methods: ['GET', 'HEAD'] },
        'horizon.masters.index': { uri: 'horizon\/api\/masters', methods: ['GET', 'HEAD'] },
        'horizon.monitoring.index': { uri: 'horizon\/api\/monitoring', methods: ['GET', 'HEAD'] },
        'horizon.monitoring.store': { uri: 'horizon\/api\/monitoring', methods: ['POST'] },
        'horizon.monitoring-tag.paginate': {
            uri: 'horizon\/api\/monitoring\/{tag}',
            methods: ['GET', 'HEAD'],
            parameters: ['tag'],
        },
        'horizon.monitoring-tag.destroy': {
            uri: 'horizon\/api\/monitoring\/{tag}',
            methods: ['DELETE'],
            wheres: { tag: '.*' },
            parameters: ['tag'],
        },
        'horizon.jobs-metrics.index': { uri: 'horizon\/api\/metrics\/jobs', methods: ['GET', 'HEAD'] },
        'horizon.jobs-metrics.show': {
            uri: 'horizon\/api\/metrics\/jobs\/{id}',
            methods: ['GET', 'HEAD'],
            parameters: ['id'],
        },
        'horizon.queues-metrics.index': { uri: 'horizon\/api\/metrics\/queues', methods: ['GET', 'HEAD'] },
        'horizon.queues-metrics.show': {
            uri: 'horizon\/api\/metrics\/queues\/{id}',
            methods: ['GET', 'HEAD'],
            parameters: ['id'],
        },
        'horizon.jobs-batches.index': { uri: 'horizon\/api\/batches', methods: ['GET', 'HEAD'] },
        'horizon.jobs-batches.show': {
            uri: 'horizon\/api\/batches\/{id}',
            methods: ['GET', 'HEAD'],
            parameters: ['id'],
        },
        'horizon.jobs-batches.retry': {
            uri: 'horizon\/api\/batches\/retry\/{id}',
            methods: ['POST'],
            parameters: ['id'],
        },
        'horizon.pending-jobs.index': { uri: 'horizon\/api\/jobs\/pending', methods: ['GET', 'HEAD'] },
        'horizon.completed-jobs.index': { uri: 'horizon\/api\/jobs\/completed', methods: ['GET', 'HEAD'] },
        'horizon.silenced-jobs.index': { uri: 'horizon\/api\/jobs\/silenced', methods: ['GET', 'HEAD'] },
        'horizon.failed-jobs.index': { uri: 'horizon\/api\/jobs\/failed', methods: ['GET', 'HEAD'] },
        'horizon.failed-jobs.show': {
            uri: 'horizon\/api\/jobs\/failed\/{id}',
            methods: ['GET', 'HEAD'],
            parameters: ['id'],
        },
        'horizon.retry-jobs.show': { uri: 'horizon\/api\/jobs\/retry\/{id}', methods: ['POST'], parameters: ['id'] },
        'horizon.jobs.show': { uri: 'horizon\/api\/jobs\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'horizon.index': {
            uri: 'horizon\/{view?}',
            methods: ['GET', 'HEAD'],
            wheres: { view: '(.*)' },
            parameters: ['view'],
        },
        'sanctum.csrf-cookie': { uri: 'sanctum\/csrf-cookie', methods: ['GET', 'HEAD'] },
        telescope: {
            uri: 'telescope\/{view?}',
            methods: ['GET', 'HEAD'],
            wheres: { view: '(.*)' },
            parameters: ['view'],
        },
        'api.v1.getStock': { uri: 'api\/XX3DWRESTO', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWREITM': { uri: 'api\/XX3DWREITM', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWL2POH': { uri: 'api\/XX3DWL2POH', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWL1POH': { uri: 'api\/XX3DWL1POH', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWLSLOC': { uri: 'api\/XX3DWLSLOC', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWLSFCY': { uri: 'api\/XX3DWLSFCY', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWLSMFG': { uri: 'api\/XX3DWLSMFG', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWLSMMK': { uri: 'api\/XX3DWLSMMK', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWLSOPE': { uri: 'api\/XX3DWLSOPE', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWLSWST': { uri: 'api\/XX3DWLSWST', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWREAPL': { uri: 'api\/XX3DWREAPL', methods: ['GET', 'HEAD'] },
        'api.v1.XX3DWRESEL': { uri: 'api\/XX3DWRESEL', methods: ['GET', 'HEAD'] },
        home: { uri: '\/', methods: ['GET', 'HEAD'] },
        'activities.index': { uri: 'activities', methods: ['GET', 'HEAD'] },
        'profile.edit': { uri: 'profile', methods: ['GET', 'HEAD'] },
        'profile.update': { uri: 'profile', methods: ['PUT', 'PATCH'] },
        'profile.update-password': { uri: 'profile\/update-password', methods: ['PATCH', 'PUT'] },
        'profile.update-site': { uri: 'profile\/update-site', methods: ['PATCH', 'PUT'] },
        'sessions.destroy': { uri: 'logout', methods: ['DELETE'] },
        login: { uri: 'login', methods: ['GET', 'HEAD'] },
        'sessions.store': { uri: 'login', methods: ['POST'] },
        'settings.edit': { uri: 'settings', methods: ['GET', 'HEAD'] },
        'settings.update': { uri: 'settings', methods: ['PATCH', 'PUT'] },
        'roles.index': { uri: 'roles', methods: ['GET', 'HEAD'] },
        'roles.store': { uri: 'roles', methods: ['POST'] },
        'roles.edit': {
            uri: 'roles\/{role}\/edit',
            methods: ['GET', 'HEAD'],
            parameters: ['role'],
            bindings: { role: 'id' },
        },
        'roles.update': {
            uri: 'roles\/{role}',
            methods: ['PUT', 'PATCH'],
            parameters: ['role'],
            bindings: { role: 'id' },
        },
        'roles.destroy': { uri: 'roles\/{role}', methods: ['DELETE'], parameters: ['role'], bindings: { role: 'id' } },
        'roles.makeDefault': {
            uri: 'roles\/{role}\/make-default',
            methods: ['POST'],
            parameters: ['role'],
            bindings: { role: 'id' },
        },
        'users.index': { uri: 'users', methods: ['GET', 'HEAD'] },
        'users.store': { uri: 'users', methods: ['POST'] },
        'users.update': {
            uri: 'users\/{user}',
            methods: ['PUT', 'PATCH'],
            parameters: ['user'],
            bindings: { user: 'id' },
        },
        'users.destroy': { uri: 'users\/{user}', methods: ['DELETE'], parameters: ['user'], bindings: { user: 'id' } },
        'users.update-password': {
            uri: 'users\/{user}\/update-password',
            methods: ['PATCH', 'PUT'],
            parameters: ['user'],
            bindings: { user: 'id' },
        },
        'users.end-sessions': {
            uri: 'users\/{user}\/end-sessions',
            methods: ['DELETE'],
            parameters: ['user'],
            bindings: { user: 'id' },
        },
        'users.sync': { uri: 'users\/sync', methods: ['POST'] },
        'reset-password.showForm': { uri: 'reset-password', methods: ['GET', 'HEAD'] },
        'reset-password.update': { uri: 'reset-password', methods: ['POST'] },
        'locations.index': { uri: 'locations', methods: ['GET', 'HEAD'] },
        'locations.store': { uri: 'locations', methods: ['POST'] },
        '@bin-move.show-form': { uri: 'bin-move', methods: ['GET', 'HEAD'] },
        '@bin-move.submit-form': { uri: 'bin-move', methods: ['POST'] },
        'api.XX3DWLSSNX': { uri: 'api\/counts', methods: ['GET', 'HEAD'] },
        'api.XX3DWLSSNL': {
            uri: 'api\/counts\/{countSession}',
            methods: ['GET', 'HEAD'],
            parameters: ['countSession'],
        },
        'assign-counts.index': { uri: 'assign-counts', methods: ['GET', 'HEAD'] },
        'assign-counts.store': { uri: 'assign-counts', methods: ['POST'] },
        'count-by-location.index': { uri: 'count-by-location', methods: ['GET', 'HEAD'] },
        'count-by-location.show': {
            uri: 'count-by-location\/{countsheet}',
            methods: ['GET', 'HEAD'],
            parameters: ['countsheet'],
            bindings: { countsheet: 'id' },
        },
        'counts.start-count': {
            uri: 'counts\/{countsheet}\/start',
            methods: ['POST'],
            parameters: ['countsheet'],
            bindings: { countsheet: 'id' },
        },
        'counts.submit-count': {
            uri: 'counts\/{countsheet}\/submit',
            methods: ['POST'],
            parameters: ['countsheet'],
            bindings: { countsheet: 'id' },
        },
        'counts.complete-location': {
            uri: 'counts\/{countsheet}\/complete-location',
            methods: ['POST'],
            parameters: ['countsheet'],
            bindings: { countsheet: 'id' },
        },
        'count-reports.index': { uri: 'count-reports', methods: ['GET', 'HEAD'] },
        '@deliveries.index': { uri: 'deliveries', methods: ['GET', 'HEAD'] },
        '@deliveries.ups.printDelivery': {
            uri: 'deliveries\/ups\/print-delivery\/{SDHNUM}',
            methods: ['POST'],
            parameters: ['SDHNUM'],
        },
        '@manage.deliveries.index': { uri: 'deliveries\/manage', methods: ['GET', 'HEAD'] },
        '@manage.deliveries.reset': { uri: 'deliveries\/{SDHNUM}\/reset', methods: ['POST'], parameters: ['SDHNUM'] },
        'intersite-transfers.show': { uri: 'intersite-transfers', methods: ['GET', 'HEAD'] },
        'intersite-transfers.store': { uri: 'intersite-transfers', methods: ['POST'] },
        '@inventory.byLocation': { uri: 'inventory\/by-location', methods: ['GET', 'HEAD'] },
        '@inventory.byItem': { uri: 'inventory\/by-item', methods: ['GET', 'HEAD'] },
        '@material-issue.create': { uri: 'material-issue', methods: ['GET', 'HEAD'] },
        '@material-issue.store': { uri: 'material-issue', methods: ['POST'] },
        '@misc-issues.index': { uri: 'misc-issues', methods: ['GET', 'HEAD'] },
        '@misc-issues.store': { uri: 'misc-issues', methods: ['POST'] },
        '@misc-receipts.show': { uri: 'misc-receipts', methods: ['GET', 'HEAD'] },
        '@misc-receipts.store': { uri: 'misc-receipts', methods: ['POST'] },
        '@picking-with-delivery.index': { uri: 'picking-with-delivery', methods: ['GET', 'HEAD'] },
        '@picking-with-delivery.show': {
            uri: 'picking-with-delivery\/{SDHNUM}',
            methods: ['GET', 'HEAD'],
            parameters: ['SDHNUM'],
        },
        '@picking-with-delivery.store': {
            uri: 'picking-with-delivery\/{SDHNUM}',
            methods: ['POST'],
            parameters: ['SDHNUM'],
        },
        '@picking-with-delivery.destroy': {
            uri: 'picking-with-delivery\/{SDHNUM}\/{assignedDeliveryLine}',
            methods: ['DELETE'],
            parameters: ['SDHNUM', 'assignedDeliveryLine'],
            bindings: { assignedDeliveryLine: 'id' },
        },
        '@picking-with-delivery.skipLine': {
            uri: 'picking-with-delivery\/{SDHNUM}\/{assignedDeliveryLine}\/skip',
            methods: ['POST'],
            parameters: ['SDHNUM', 'assignedDeliveryLine'],
            bindings: { assignedDeliveryLine: 'id' },
        },
        '@picking-with-delivery.summary.show': {
            uri: 'picking-with-delivery\/{SDHNUM}\/summary',
            methods: ['GET', 'HEAD'],
            parameters: ['SDHNUM'],
        },
        '@picking-with-delivery.summary.store': {
            uri: 'picking-with-delivery\/{SDHNUM}\/summary',
            methods: ['POST'],
            parameters: ['SDHNUM'],
        },
        '@production-tracking.create': { uri: 'production-tracking', methods: ['GET', 'HEAD'] },
        '@production-tracking.store': { uri: 'production-tracking', methods: ['POST'] },
        'putaway.index': { uri: 'putaway', methods: ['GET', 'HEAD'] },
        'putaway.store': { uri: 'putaway', methods: ['POST'] },
        'putaway.destroy': {
            uri: 'putaway\/{putaway}',
            methods: ['DELETE'],
            parameters: ['putaway'],
            bindings: { putaway: 'id' },
        },
        'putaway-details.index': {
            uri: 'putaway\/{putaway}\/details',
            methods: ['GET', 'HEAD'],
            parameters: ['putaway'],
            bindings: { putaway: 'id' },
        },
        'putaway-details.store': {
            uri: 'putaway\/{putaway}\/details',
            methods: ['POST'],
            parameters: ['putaway'],
            bindings: { putaway: 'id' },
        },
        'putaway-details.destroy': {
            uri: 'putaway\/{putaway}\/details\/{detail}',
            methods: ['DELETE'],
            parameters: ['putaway', 'detail'],
            bindings: { putaway: 'id', detail: 'id' },
        },
        'putaway.submit': {
            uri: 'putaway\/{putaway}\/submit\/{location}',
            methods: ['POST'],
            parameters: ['putaway', 'location'],
            bindings: { putaway: 'id' },
        },
        'putaway.process.index': {
            uri: 'putaway\/{putaway}\/process',
            methods: ['GET', 'HEAD'],
            parameters: ['putaway'],
            bindings: { putaway: 'id' },
        },
        '@receiving.index': { uri: 'receiving', methods: ['GET', 'HEAD'] },
        '@receiving.store': { uri: 'receiving', methods: ['POST'] },
        '@receiving.destroy': {
            uri: 'receiving\/{receiving}',
            methods: ['DELETE'],
            parameters: ['receiving'],
            bindings: { receiving: 'id' },
        },
        '@receiving.detail.index': {
            uri: 'receiving\/{receipt}\/details',
            methods: ['GET', 'HEAD'],
            parameters: ['receipt'],
            bindings: { receipt: 'id' },
        },
        '@receiving.detail.store': {
            uri: 'receiving\/{receipt}\/details',
            methods: ['POST'],
            parameters: ['receipt'],
            bindings: { receipt: 'id' },
        },
        '@receiving.detail.destroy': {
            uri: 'receiving\/{receipt}\/details\/{detail}',
            methods: ['DELETE'],
            parameters: ['receipt', 'detail'],
            bindings: { receipt: 'id', detail: 'id' },
        },
        '@receiving.submit': {
            uri: 'receiving\/{receipt}\/submit',
            methods: ['POST'],
            parameters: ['receipt'],
            bindings: { receipt: 'id' },
        },
        '@reintegration.create': { uri: 'reintegration', methods: ['GET', 'HEAD'] },
        '@reintegration.store': { uri: 'reintegration', methods: ['POST'] },
        'work-order.start.index': { uri: 'work-order\/start', methods: ['GET', 'HEAD'] },
        'work-order.start.store': { uri: 'work-order\/start', methods: ['POST'] },
        'work-order.stop.index': { uri: 'work-order\/stop', methods: ['GET', 'HEAD'] },
        'work-order.stop.store': { uri: 'work-order\/stop', methods: ['POST'] },
        'clock-in.index': { uri: 'clock-in', methods: ['GET', 'HEAD'] },
        'clock-in.store': { uri: 'clock-in', methods: ['POST'] },
        'clock-out.index': { uri: 'clock-out', methods: ['GET', 'HEAD'] },
        'clock-out.store': { uri: 'clock-out', methods: ['POST'] },
        '@split-pallets.index': { uri: 'split-pallets', methods: ['GET', 'HEAD'] },
        '@split-pallets.store': { uri: 'split-pallets', methods: ['POST'] },
        '@stock-change.create': { uri: 'stock-change', methods: ['GET', 'HEAD'] },
        '@stock-change.store': { uri: 'stock-change', methods: ['POST'] },
        '@truck-loading.create': { uri: 'truck-loading', methods: ['GET', 'HEAD'] },
        '@truck-loading.store': { uri: 'truck-loading', methods: ['POST'] },
        'storage.local': {
            uri: 'storage\/{path}',
            methods: ['GET', 'HEAD'],
            wheres: { path: '.*' },
            parameters: ['path'],
        },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
